name: "Podcast Generator"
author: "Arshia Aflaki"
description: "Generated a feed for our Podcast"

runs: 
  using: "docker"
  image: "Dockerfile"
barnding: 
  icon: "git-branch"
  color: "red"
inputs:
  email: 
    description: "The Comiter's email address"
    required: true
    default: ${{ github.actor }}@localhost
  name: 
    description: "The commiters name"
    required: true
    default: ${{ github.actor }}
